POST http://localhost:8080/user/Jack/create
Content-Type: application/json

{
  "fullname": "Captain Jack Sparrow",
  "about": "This is the day you will always remember as the day that you almost caught Captain Jack Sparrow!",
  "email": "captaina@blackpearl.sea"
}

################################

GET http://localhost:8080/user/Jack/profile

###############################

POST http://localhost:8080/user/Jack/profile
Content-Type: application/json

{
  "fullname": "Captain Jack Sparrow",
  "about": "This is the day you will always remember as the day that you almost caught Captain Jack Sparrow!",
  "email": "captaina@blackpearl.sea"
}
